"""initial

Revision ID: 02e05ae31937
Revises: 2423c75a2d38
Create Date: 2023-05-17 12:58:07.806876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "02e05ae31937"
down_revision = "2423c75a2d38"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
