"""initial

Revision ID: 08e900478410
Revises: c2b7229bbc81
Create Date: 2023-05-18 16:00:55.086419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "08e900478410"
down_revision = "c2b7229bbc81"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
