"""initial

Revision ID: 2423c75a2d38
Revises: 96e6ed019b1a
Create Date: 2023-05-17 12:50:46.278803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2423c75a2d38"
down_revision = "96e6ed019b1a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
