"""initial

Revision ID: 2679924bbf76
Revises: b1fe8fd4f307
Create Date: 2023-05-17 13:10:28.230612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2679924bbf76"
down_revision = "b1fe8fd4f307"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("question", sa.Column("date_add", sa.DateTime(), nullable=False))
    op.drop_column("question", "counter")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "question",
        sa.Column("counter", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("question", "date_add")
    # ### end Alembic commands ###
