"""initial

Revision ID: 7bcd729f2e87
Revises: cb12ddfeae3a
Create Date: 2023-05-17 18:10:54.305621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7bcd729f2e87"
down_revision = "cb12ddfeae3a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
