"""initial

Revision ID: 92d8faffd679
Revises:
Create Date: 2023-05-16 16:39:33.324145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "92d8faffd679"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("answer", sa.String(length=5000), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("question", sa.String(length=5000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question")
    # ### end Alembic commands ###
