"""empty message

Revision ID: 96e6ed019b1a
Revises: 92d8faffd679
Create Date: 2023-05-17 12:33:52.831956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96e6ed019b1a"
down_revision = "92d8faffd679"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("question", sa.Column("counter", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("question", "counter")
    # ### end Alembic commands ###
