"""initial

Revision ID: b1fe8fd4f307
Revises: 02e05ae31937
Create Date: 2023-05-17 12:59:37.308253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1fe8fd4f307"
down_revision = "02e05ae31937"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
