"""initial

Revision ID: c2b7229bbc81
Revises: ef7e3562b33f
Create Date: 2023-05-18 15:51:34.051820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c2b7229bbc81"
down_revision = "ef7e3562b33f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
