"""initial

Revision ID: cb12ddfeae3a
Revises: 2679924bbf76
Create Date: 2023-05-17 17:17:37.371323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cb12ddfeae3a"
down_revision = "2679924bbf76"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
