"""initial

Revision ID: d72f2ac1b0b6
Revises: 08e900478410
Create Date: 2023-05-18 16:04:33.651444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d72f2ac1b0b6"
down_revision = "08e900478410"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
