"""initial

Revision ID: ef7e3562b33f
Revises: 7bcd729f2e87
Create Date: 2023-05-18 15:42:57.036501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef7e3562b33f"
down_revision = "7bcd729f2e87"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
